### ISSUE TITLE
Deleting values

### ISSUE THREAD

**Issue by JamenMarz** [jdf221/PMCPlusPlus#1]
I saw your comment stating that there wasn't a method to delete values in Greasemonkey, but I did a quick search online and found this resource: 
http://wiki.greasespot.net/GM_deleteValue
Related: https://github.com/jdf221/PMCPlusPlus/blob/master/pmc%2B%2B.user.js#L41-L45

**Comment by jdf221** [comment]
I don't even use that function :P Got the code from http://userscripts-mirror.org/scripts/show/68559. Don't knwo why I dind't leave credit. Gonna edit that now.
