### ISSUE TITLE
jQuery?

### ISSUE THREAD

**Issue by JamenMarz** [jdf221/PMCPlusPlus#2]
I noticed you have the jQuery script with the script, but you're not using it.  :open_mouth: 

Also, PlanetMinecraft already has jQuery, if you inject the script after the web browser has fetched and parsed the jQuery script, you don't even have to have jQuery included in the package.

**Comment by jdf221** [comment]
Randomly PMC would not load jquery for me. LIke at random times I would get $ is not defined.

But that could be the way TamperMonkey loaded the script. Haven't had the problem with the Chrome extension.
